---
#
##
### Written by Maxence Maireaux (maxence.maireaux@wescale.fr)
##
#
- hosts: localhost
  become: no

  vars:
    include_dir: "{{ playbook_dir }}/inc"
  pre_tasks:
    - include_tasks: "{{ include_dir }}/_init.yml"
    - include_tasks: "{{ include_dir }}/{{ osf_provider }}/_init.yml"

  tasks:
    - include_tasks: "{{ include_dir }}/_ansible_dependencies.yml"
    - include_tasks: "{{ include_dir }}/{{ osf_provider }}/_packer_build.yml"
    - include_tasks: "{{ include_dir }}/_packer_get_id.yml"

  post_tasks:

    - include_tasks: "{{ include_dir }}/{{ osf_provider }}/_ami_sharing.yml"

    - name: "Build success - awesomeness, joy, that sort of feelings"
      debug:
        msg: >-
          Image build is a success.
          The AMI and SNAPSHOT is now in your AWS account and shared with bro-accounts.
          AMI : {{ ami_id }}
